services:
  - type: web
    name: bit-complaint-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://bit-complaint-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: bit-complaint-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false